/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#134a36",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002117",
        "on-primary-fixed-variant": "#2a5a44",
        "on-primary-container": "#ecf1ef",
        "primary-fixed": "#dce4e1",
        "primary-fixed-dim": "#b8c9c3",
        "primary-container": "#0f3b2b",
        surface: "#f3f7f2",
        "surface-dim": "#d2dad4",
        "surface-bright": "#f3f7f2",
        "surface-tint": "#134a36",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e8ece8",
        "surface-container": "#d8dfd9",
        "surface-container-high": "#cbd2cc",
        "surface-container-highest": "#bec6c0",
        "surface-variant": "#dde4de",
        "on-surface": "#0f1f17",
        "on-surface-variant": "#3f4a42",
        outline: "#707b73",
        "outline-variant": "#c8d0c6",
        "inverse-surface": "#0f1f17",
        "inverse-on-surface": "#eef3ee",
        "inverse-primary": "#b8c9c3",
        secondary: "#475569",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#475569",
        "on-secondary-fixed": "#0f172a",
        "on-secondary-fixed-variant": "#334155",
        "secondary-fixed": "#e2e8f0",
        "secondary-fixed-dim": "#cbd5e1",
        "secondary-container": "#e2e8f0",
        tertiary: "#ec4899",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#fce7f3",
        "on-tertiary-container": "#4d002b",
        "on-tertiary-fixed": "#fbcfe8",
        "on-tertiary-fixed-dim": "#f472b6",
        error: "#ef4444",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        "on-background": "#0f1f17",
        brand: "#134a36",
      },
      fontFamily: {
        "display-lg": ['"Lexend"', "sans-serif"],
        "headline-lg": ['"Lexend"', "sans-serif"],
        "headline-lg-mobile": ['"Lexend"', "sans-serif"],
        "headline-md": ['"Lexend"', "sans-serif"],
        "body-sm": ['"Figtree"', "sans-serif"],
        "body-md": ['"Figtree"', "sans-serif"],
        "body-lg": ['"Figtree"', "sans-serif"],
        "label-sm": ['"Figtree"', "sans-serif"],
        "label-md": ['"Figtree"', "sans-serif"],
        body: ['"Figtree"', "sans-serif"],
        display: ['"Lexend"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["88px", { lineHeight: "96px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
        container: "1280px",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        none: "0",
      },
    },
  },
  plugins: [],
};
