/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0053db",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-container": "#eeefff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "primary-container": "#2563eb",
        surface: "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#0053db",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-surface": "#00174b",
        "on-surface-variant": "#434655",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
        "inverse-surface": "#00174b",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#b4c5ff",
        secondary: "#545f73",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#586377",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-fixed": "#d8e3fb",
        "secondary-fixed-dim": "#bcc7de",
        "secondary-container": "#d5e0f8",
        tertiary: "#006242",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007d55",
        "on-tertiary-container": "#bdffdb",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-background": "#00174b",
      },
      fontFamily: {
        "display-lg": ['"Lexend"', "sans-serif"],
        "headline-lg": ['"Lexend"', "sans-serif"],
        "headline-lg-mobile": ['"Lexend"', "sans-serif"],
        "headline-md": ['"Lexend"', "sans-serif"],
        "body-sm": ['"Figtree"', "sans-serif"],
        "body-md": ['"Figtree"', "sans-serif"],
        "body-lg": ['"Figtree"', "sans-serif"],
        "label-sm": ['"Figtree"', "sans-serif"],
        "label-md": ['"Figtree"', "sans-serif"],
        body: ['"Figtree"', "sans-serif"],
        display: ['"Lexend"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["88px", { lineHeight: "96px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
        container: "1280px",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        none: "0",
      },
    },
  },
  plugins: [],
};
