/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0e4a5a",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#051f26",
        "on-primary-fixed-variant": "#175b6e",
        "on-primary-container": "#e3f3f7",
        "primary-fixed": "#cae7ef",
        "primary-fixed-dim": "#98cedc",
        "primary-container": "#093743",
        surface: "#f2f8fa",
        "surface-dim": "#cfdedf",
        "surface-bright": "#f7fbfc",
        "surface-tint": "#0e4a5a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ebf4f6",
        "surface-container": "#dcecee",
        "surface-container-high": "#d0e4e7",
        "surface-container-highest": "#c3dade",
        "surface-variant": "#d8e8eb",
        "on-surface": "#0c1b1f",
        "on-surface-variant": "#3b4d52",
        outline: "#6a7e84",
        "outline-variant": "#c0d4d9",
        "inverse-surface": "#0c1b1f",
        "inverse-on-surface": "#ebf5f7",
        "inverse-primary": "#4ec3dd",
        secondary: "#485960",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#2f4047",
        "on-secondary-fixed": "#0c1b1f",
        "on-secondary-fixed-variant": "#304249",
        "secondary-fixed": "#ddebee",
        "secondary-fixed-dim": "#b8ced4",
        "secondary-container": "#e1edf0",
        tertiary: "#0891b2",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#cffafe",
        "on-tertiary-container": "#164e63",
        "on-tertiary-fixed": "#164e63",
        "on-tertiary-fixed-dim": "#0e7490",
        "tertiary-fixed": "#cffafe",
        "tertiary-fixed-dim": "#a5f3fc",
        error: "#ef4444",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        "on-background": "#0c1b1f",
        brand: "#0e4a5a",
      },
      fontFamily: {
        "display-lg": ['"Lexend"', "sans-serif"],
        "headline-lg": ['"Lexend"', "sans-serif"],
        "headline-lg-mobile": ['"Lexend"', "sans-serif"],
        "headline-md": ['"Lexend"', "sans-serif"],
        "body-sm": ['"Figtree"', "sans-serif"],
        "body-md": ['"Figtree"', "sans-serif"],
        "body-lg": ['"Figtree"', "sans-serif"],
        "label-sm": ['"Figtree"', "sans-serif"],
        "label-md": ['"Figtree"', "sans-serif"],
        body: ['"Figtree"', "sans-serif"],
        display: ['"Lexend"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["88px", { lineHeight: "96px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1280px",
        container: "1280px",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        none: "0",
      },
    },
  },
  plugins: [],
};
